name: CodeLyokoUHC
version: 1.0
author: Av32000/RedFly32
main: fr.av.codelyokouhc.Main
depend: [WorldEdit]
commands:
  tpspawn:
    description: Téléporte tous les joueurs au spawn
    permission: codelyoko.admin

  startGame:
    description: Lance le jeu
    permission: codelyoko.admin

  setGameSpawn:
    description: Set le point d'apparition des joueurs lorsque le jeu se lance
    permission: codelyoko.admin

  setLyokoSpawn:
    description: Set le point de spawn dans le lyoko
    permission: codelyoko.admin

  getRole:
    description: Retourne le rôle d'un joueur
    permission: codelyoko.admin

  lyokoTp:
    description: Permet de se téléporter dans la dimension du lyoko
    permission: codelyoko.admin

  spawn:
    description: Téléporte le joueur au spawn
    permission: codelyoko.admin

  cl:
    description: Commandes relatives au CodeLyoko-UHC