name: CodeLyokoUHC
version: 1.0
author: Av32000/RedFly32
main: fr.av.codelyokouhc.Main
depend: [WorldEdit]
commands:
  tpspawn:
    description: Téléporte tous les joueurs au spawn
    permission: codelyoko.admin

  startGame:
    description: Lance le jeu
    permission: codelyoko.admin

  setGameSpawn:
    description: Set le point d'apparition des joueurs lorsque le jeu se lance
    permission: codelyoko.admin

  setLyokoSpawn:
    description: Srt le point de spawn dans le lyoko
    permission: codelyoko.admin

  overworld:
    description: Téléporte un joueur du loko vers l'overworld